
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/E-Commerce
    username: postgres
    password: jakobe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/commerce
          jwk-set-uri: http://localhost:8081/auth/realms/commerce/protocol/openid-connect/certs




server:
  port: 8080
  error:
    include-stacktrace: always